name: Build Scripts Zip

on:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create artifact
        run: |
          mkdir output
          #zip -r output/scripts.zip powershell README.md
          cp README.md output/
          cp -r powershell output/

      - uses: actions/upload-artifact@v4
        with:
          name: scripts-zip
          path: output/scripts.zip