name: Build Scripts Zip

on:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare output directory
        run: |
          mkdir output
          cp -r powershell/* output/
          cp README.md output/

      - uses: actions/upload-artifact@v4
        with:
          name: scripts-zip
          path: output/**